-- The node's one `content` field becomes the 53 typed attribute columns of the
-- roster, and the rules that were the daemon's alone become 169 CHECKs. SQLite
-- can neither drop a NOT NULL column nor add a constraint, so both tables are
-- rebuilt rather than altered.
--
-- WHAT HAPPENS TO THE ROWS ALREADY THERE. The owner's decision, recorded here
-- because no reader could recover it from the SQL: `content` is dropped with
-- its values and is NOT moved into any prose attribute; every required slot is
-- filled with a placeholder — 'test text', or a vocabulary's first value for a
-- `choice` — so that a row already written satisfies rules it was written
-- before; every optional slot is left NULL. A node of a type the canon does not
-- name is deleted with the edges that reached it: it can satisfy no roster, so
-- there is nothing to convert it into.
--
-- WHY THE ORDER IS WHAT IT IS. The migrator runs every pending file in ONE
-- transaction, and SQLite ignores `PRAGMA foreign_keys` inside one, so the
-- generator's toggles around the rebuild are removed and the statement order
-- carries the whole burden instead. The old `edges` names no foreign key, so
-- `nodes` can be rebuilt first; the new `edges` does, so it is built after
-- the new `nodes` is in place under its own name, and it takes only the edges
-- whose two endpoints survived.
--
-- The duplicate rule is new as well, so the copy keeps the FIRST edge of each
-- (from, type, to) triple by id — a ULID, so the lowest id is the one drawn
-- earliest — and drops any later redraw of the same relation.
DELETE FROM `edges` WHERE `from_id` IN (SELECT `id` FROM `nodes` WHERE `type` NOT IN ('Term', 'DomainEntity', 'Goal', 'Actor', 'UseCase', 'Scenario', 'SystemResponsibility', 'Requirement', 'AcceptanceCriterion', 'Constraint', 'ModuleDesign', 'Interface', 'DataSchema', 'ImplementationTask', 'Journal', 'WorkLog', 'Evidence', 'Commit', 'VerificationReport', 'Finding', 'Assumption', 'Question', 'Decision')) OR `to_id` IN (SELECT `id` FROM `nodes` WHERE `type` NOT IN ('Term', 'DomainEntity', 'Goal', 'Actor', 'UseCase', 'Scenario', 'SystemResponsibility', 'Requirement', 'AcceptanceCriterion', 'Constraint', 'ModuleDesign', 'Interface', 'DataSchema', 'ImplementationTask', 'Journal', 'WorkLog', 'Evidence', 'Commit', 'VerificationReport', 'Finding', 'Assumption', 'Question', 'Decision'));
--> statement-breakpoint
DELETE FROM `nodes` WHERE `type` NOT IN ('Term', 'DomainEntity', 'Goal', 'Actor', 'UseCase', 'Scenario', 'SystemResponsibility', 'Requirement', 'AcceptanceCriterion', 'Constraint', 'ModuleDesign', 'Interface', 'DataSchema', 'ImplementationTask', 'Journal', 'WorkLog', 'Evidence', 'Commit', 'VerificationReport', 'Finding', 'Assumption', 'Question', 'Decision');
--> statement-breakpoint
CREATE TABLE `__new_nodes` (
	`id` text PRIMARY KEY NOT NULL,
	`type` text NOT NULL,
	`short_name` text NOT NULL,
	`name` text NOT NULL,
	`actor_type` text,
	`aliases` text,
	`answer` text,
	`applies_when` text,
	`basis` text,
	`behavior_design_description` text,
	`benchmark` text,
	`benefit` text,
	`claim` text,
	`constraint_type` text,
	`contract_description` text,
	`coverage` text,
	`decision` text,
	`definition` text,
	`definition_of_done` text,
	`deliverables` text,
	`description` text,
	`evaluation_process` text,
	`finding_type` text,
	`goal` text,
	`handover` text,
	`interface_type` text,
	`key_attributes` text,
	`message` text,
	`narrative` text,
	`non_goals` text,
	`objective` text,
	`outcome` text,
	`performer` text,
	`period` text,
	`postconditions` text,
	`preconditions` text,
	`priority` text,
	`protocol` text,
	`question` text,
	`rationale` text,
	`requirement_type` text,
	`responsibility_type` text,
	`risks` text,
	`role_description` text,
	`scenario_type` text,
	`scope` text,
	`severity` text,
	`sha` text,
	`state` text,
	`statement` text,
	`steps` text,
	`structural_design_description` text,
	`success_measure` text,
	`testimony` text,
	`trigger` text,
	`verdict` text,
	`work_summary` text,
	`created_at` integer NOT NULL,
	`updated_at` integer DEFAULT 0 NOT NULL,
	CONSTRAINT "nodes_type_known" CHECK("type" IN ('Term', 'DomainEntity', 'Goal', 'Actor', 'UseCase', 'Scenario', 'SystemResponsibility', 'Requirement', 'AcceptanceCriterion', 'Constraint', 'ModuleDesign', 'Interface', 'DataSchema', 'ImplementationTask', 'Journal', 'WorkLog', 'Evidence', 'Commit', 'VerificationReport', 'Finding', 'Assumption', 'Question', 'Decision')),
	CONSTRAINT "nodes_short_name_nonempty" CHECK("short_name" <> ''),
	CONSTRAINT "nodes_name_nonempty" CHECK("name" <> ''),
	CONSTRAINT "nodes_actor_type_typed" CHECK("actor_type" IS NULL OR "type" IN ('Actor')),
	CONSTRAINT "nodes_aliases_typed" CHECK("aliases" IS NULL OR "type" IN ('Term')),
	CONSTRAINT "nodes_answer_typed" CHECK("answer" IS NULL OR "type" IN ('Question')),
	CONSTRAINT "nodes_applies_when_typed" CHECK("applies_when" IS NULL OR "type" IN ('Constraint')),
	CONSTRAINT "nodes_basis_typed" CHECK("basis" IS NULL OR "type" IN ('Assumption')),
	CONSTRAINT "nodes_behavior_design_description_typed" CHECK("behavior_design_description" IS NULL OR "type" IN ('ModuleDesign')),
	CONSTRAINT "nodes_benchmark_typed" CHECK("benchmark" IS NULL OR "type" IN ('AcceptanceCriterion')),
	CONSTRAINT "nodes_benefit_typed" CHECK("benefit" IS NULL OR "type" IN ('UseCase')),
	CONSTRAINT "nodes_claim_typed" CHECK("claim" IS NULL OR "type" IN ('Evidence')),
	CONSTRAINT "nodes_constraint_type_typed" CHECK("constraint_type" IS NULL OR "type" IN ('Constraint')),
	CONSTRAINT "nodes_contract_description_typed" CHECK("contract_description" IS NULL OR "type" IN ('Interface')),
	CONSTRAINT "nodes_coverage_typed" CHECK("coverage" IS NULL OR "type" IN ('VerificationReport')),
	CONSTRAINT "nodes_decision_typed" CHECK("decision" IS NULL OR "type" IN ('Decision')),
	CONSTRAINT "nodes_definition_typed" CHECK("definition" IS NULL OR "type" IN ('Term')),
	CONSTRAINT "nodes_definition_of_done_typed" CHECK("definition_of_done" IS NULL OR "type" IN ('ImplementationTask')),
	CONSTRAINT "nodes_deliverables_typed" CHECK("deliverables" IS NULL OR "type" IN ('ImplementationTask')),
	CONSTRAINT "nodes_description_typed" CHECK("description" IS NULL OR "type" IN ('DomainEntity', 'Goal', 'Actor', 'UseCase', 'SystemResponsibility', 'Requirement', 'AcceptanceCriterion', 'Constraint', 'DataSchema', 'ImplementationTask', 'Finding', 'Assumption', 'Question', 'Decision')),
	CONSTRAINT "nodes_evaluation_process_typed" CHECK("evaluation_process" IS NULL OR "type" IN ('AcceptanceCriterion')),
	CONSTRAINT "nodes_finding_type_typed" CHECK("finding_type" IS NULL OR "type" IN ('Finding')),
	CONSTRAINT "nodes_goal_typed" CHECK("goal" IS NULL OR "type" IN ('ImplementationTask')),
	CONSTRAINT "nodes_handover_typed" CHECK("handover" IS NULL OR "type" IN ('Journal')),
	CONSTRAINT "nodes_interface_type_typed" CHECK("interface_type" IS NULL OR "type" IN ('Interface')),
	CONSTRAINT "nodes_key_attributes_typed" CHECK("key_attributes" IS NULL OR "type" IN ('DomainEntity')),
	CONSTRAINT "nodes_message_typed" CHECK("message" IS NULL OR "type" IN ('Commit')),
	CONSTRAINT "nodes_narrative_typed" CHECK("narrative" IS NULL OR "type" IN ('WorkLog')),
	CONSTRAINT "nodes_non_goals_typed" CHECK("non_goals" IS NULL OR "type" IN ('ImplementationTask')),
	CONSTRAINT "nodes_objective_typed" CHECK("objective" IS NULL OR "type" IN ('Journal')),
	CONSTRAINT "nodes_outcome_typed" CHECK("outcome" IS NULL OR "type" IN ('WorkLog')),
	CONSTRAINT "nodes_performer_typed" CHECK("performer" IS NULL OR "type" IN ('Journal')),
	CONSTRAINT "nodes_period_typed" CHECK("period" IS NULL OR "type" IN ('Journal')),
	CONSTRAINT "nodes_postconditions_typed" CHECK("postconditions" IS NULL OR "type" IN ('Scenario', 'Interface')),
	CONSTRAINT "nodes_preconditions_typed" CHECK("preconditions" IS NULL OR "type" IN ('Scenario', 'Interface')),
	CONSTRAINT "nodes_priority_typed" CHECK("priority" IS NULL OR "type" IN ('UseCase', 'Requirement')),
	CONSTRAINT "nodes_protocol_typed" CHECK("protocol" IS NULL OR "type" IN ('Interface')),
	CONSTRAINT "nodes_question_typed" CHECK("question" IS NULL OR "type" IN ('Question')),
	CONSTRAINT "nodes_rationale_typed" CHECK("rationale" IS NULL OR "type" IN ('Requirement', 'Constraint', 'ModuleDesign', 'Decision')),
	CONSTRAINT "nodes_requirement_type_typed" CHECK("requirement_type" IS NULL OR "type" IN ('Requirement')),
	CONSTRAINT "nodes_responsibility_type_typed" CHECK("responsibility_type" IS NULL OR "type" IN ('SystemResponsibility')),
	CONSTRAINT "nodes_risks_typed" CHECK("risks" IS NULL OR "type" IN ('ImplementationTask')),
	CONSTRAINT "nodes_role_description_typed" CHECK("role_description" IS NULL OR "type" IN ('ModuleDesign')),
	CONSTRAINT "nodes_scenario_type_typed" CHECK("scenario_type" IS NULL OR "type" IN ('Scenario')),
	CONSTRAINT "nodes_scope_typed" CHECK("scope" IS NULL OR "type" IN ('ImplementationTask')),
	CONSTRAINT "nodes_severity_typed" CHECK("severity" IS NULL OR "type" IN ('Finding')),
	CONSTRAINT "nodes_sha_typed" CHECK("sha" IS NULL OR "type" IN ('Commit')),
	CONSTRAINT "nodes_state_typed" CHECK("state" IS NULL OR "type" IN ('Question')),
	CONSTRAINT "nodes_statement_typed" CHECK("statement" IS NULL OR "type" IN ('Goal', 'SystemResponsibility', 'Requirement', 'AcceptanceCriterion', 'Constraint', 'Finding', 'Assumption')),
	CONSTRAINT "nodes_steps_typed" CHECK("steps" IS NULL OR "type" IN ('Scenario')),
	CONSTRAINT "nodes_structural_design_description_typed" CHECK("structural_design_description" IS NULL OR "type" IN ('ModuleDesign')),
	CONSTRAINT "nodes_success_measure_typed" CHECK("success_measure" IS NULL OR "type" IN ('Goal')),
	CONSTRAINT "nodes_testimony_typed" CHECK("testimony" IS NULL OR "type" IN ('VerificationReport')),
	CONSTRAINT "nodes_trigger_typed" CHECK("trigger" IS NULL OR "type" IN ('VerificationReport')),
	CONSTRAINT "nodes_verdict_typed" CHECK("verdict" IS NULL OR "type" IN ('Evidence')),
	CONSTRAINT "nodes_work_summary_typed" CHECK("work_summary" IS NULL OR "type" IN ('Journal')),
	CONSTRAINT "nodes_actor_type_known" CHECK("actor_type" IS NULL OR "actor_type" IN ('user', 'external_system', 'ego_system')),
	CONSTRAINT "nodes_constraint_type_known" CHECK("constraint_type" IS NULL OR "constraint_type" IN ('platform', 'technology', 'hardware', 'interface', 'data', 'performance', 'security', 'safety_reliability', 'regulatory_compliance', 'operational', 'development', 'organizational')),
	CONSTRAINT "nodes_finding_type_known" CHECK("finding_type" IS NULL OR "finding_type" IN ('missing', 'partial', 'contradicts', 'unrequested')),
	CONSTRAINT "nodes_interface_type_known" CHECK("interface_type" IS NULL OR "interface_type" IN ('api', 'event', 'message', 'file', 'database', 'hardware', 'user', 'network', 'library', 'cli')),
	CONSTRAINT "nodes_priority_known" CHECK("priority" IS NULL OR "priority" IN ('high', 'medium', 'low')),
	CONSTRAINT "nodes_requirement_type_known" CHECK("requirement_type" IS NULL OR "requirement_type" IN ('functional', 'non_functional')),
	CONSTRAINT "nodes_responsibility_type_known" CHECK("responsibility_type" IS NULL OR "responsibility_type" IN ('core', 'supplementary')),
	CONSTRAINT "nodes_scenario_type_known" CHECK("scenario_type" IS NULL OR "scenario_type" IN ('main', 'alternative', 'exception')),
	CONSTRAINT "nodes_severity_known" CHECK("severity" IS NULL OR "severity" IN ('critical', 'high', 'medium', 'low')),
	CONSTRAINT "nodes_state_known" CHECK("state" IS NULL OR "state" IN ('open', 'closed')),
	CONSTRAINT "nodes_verdict_known" CHECK("verdict" IS NULL OR "verdict" IN ('pending', 'approved', 'rejected')),
	CONSTRAINT "nodes_term_definition_required" CHECK("type" <> 'Term' OR "definition" IS NOT NULL),
	CONSTRAINT "nodes_domainentity_description_required" CHECK("type" <> 'DomainEntity' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_goal_statement_required" CHECK("type" <> 'Goal' OR "statement" IS NOT NULL),
	CONSTRAINT "nodes_actor_description_required" CHECK("type" <> 'Actor' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_actor_actor_type_required" CHECK("type" <> 'Actor' OR "actor_type" IS NOT NULL),
	CONSTRAINT "nodes_usecase_description_required" CHECK("type" <> 'UseCase' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_usecase_benefit_required" CHECK("type" <> 'UseCase' OR "benefit" IS NOT NULL),
	CONSTRAINT "nodes_usecase_priority_required" CHECK("type" <> 'UseCase' OR "priority" IS NOT NULL),
	CONSTRAINT "nodes_scenario_scenario_type_required" CHECK("type" <> 'Scenario' OR "scenario_type" IS NOT NULL),
	CONSTRAINT "nodes_scenario_preconditions_required" CHECK("type" <> 'Scenario' OR "preconditions" IS NOT NULL),
	CONSTRAINT "nodes_scenario_steps_required" CHECK("type" <> 'Scenario' OR "steps" IS NOT NULL),
	CONSTRAINT "nodes_scenario_postconditions_required" CHECK("type" <> 'Scenario' OR "postconditions" IS NOT NULL),
	CONSTRAINT "nodes_systemresponsibility_statement_required" CHECK("type" <> 'SystemResponsibility' OR "statement" IS NOT NULL),
	CONSTRAINT "nodes_systemresponsibility_description_required" CHECK("type" <> 'SystemResponsibility' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_systemresponsibility_responsibility_type_required" CHECK("type" <> 'SystemResponsibility' OR "responsibility_type" IS NOT NULL),
	CONSTRAINT "nodes_requirement_statement_required" CHECK("type" <> 'Requirement' OR "statement" IS NOT NULL),
	CONSTRAINT "nodes_requirement_description_required" CHECK("type" <> 'Requirement' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_requirement_requirement_type_required" CHECK("type" <> 'Requirement' OR "requirement_type" IS NOT NULL),
	CONSTRAINT "nodes_requirement_priority_required" CHECK("type" <> 'Requirement' OR "priority" IS NOT NULL),
	CONSTRAINT "nodes_acceptancecriterion_statement_required" CHECK("type" <> 'AcceptanceCriterion' OR "statement" IS NOT NULL),
	CONSTRAINT "nodes_acceptancecriterion_description_required" CHECK("type" <> 'AcceptanceCriterion' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_acceptancecriterion_evaluation_process_required" CHECK("type" <> 'AcceptanceCriterion' OR "evaluation_process" IS NOT NULL),
	CONSTRAINT "nodes_constraint_statement_required" CHECK("type" <> 'Constraint' OR "statement" IS NOT NULL),
	CONSTRAINT "nodes_constraint_description_required" CHECK("type" <> 'Constraint' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_constraint_constraint_type_required" CHECK("type" <> 'Constraint' OR "constraint_type" IS NOT NULL),
	CONSTRAINT "nodes_moduledesign_role_description_required" CHECK("type" <> 'ModuleDesign' OR "role_description" IS NOT NULL),
	CONSTRAINT "nodes_moduledesign_structural_design_description_required" CHECK("type" <> 'ModuleDesign' OR "structural_design_description" IS NOT NULL),
	CONSTRAINT "nodes_moduledesign_behavior_design_description_required" CHECK("type" <> 'ModuleDesign' OR "behavior_design_description" IS NOT NULL),
	CONSTRAINT "nodes_interface_contract_description_required" CHECK("type" <> 'Interface' OR "contract_description" IS NOT NULL),
	CONSTRAINT "nodes_interface_interface_type_required" CHECK("type" <> 'Interface' OR "interface_type" IS NOT NULL),
	CONSTRAINT "nodes_dataschema_description_required" CHECK("type" <> 'DataSchema' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_implementationtask_description_required" CHECK("type" <> 'ImplementationTask' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_implementationtask_goal_required" CHECK("type" <> 'ImplementationTask' OR "goal" IS NOT NULL),
	CONSTRAINT "nodes_implementationtask_scope_required" CHECK("type" <> 'ImplementationTask' OR "scope" IS NOT NULL),
	CONSTRAINT "nodes_implementationtask_deliverables_required" CHECK("type" <> 'ImplementationTask' OR "deliverables" IS NOT NULL),
	CONSTRAINT "nodes_implementationtask_definition_of_done_required" CHECK("type" <> 'ImplementationTask' OR "definition_of_done" IS NOT NULL),
	CONSTRAINT "nodes_journal_period_required" CHECK("type" <> 'Journal' OR "period" IS NOT NULL),
	CONSTRAINT "nodes_journal_performer_required" CHECK("type" <> 'Journal' OR "performer" IS NOT NULL),
	CONSTRAINT "nodes_journal_objective_required" CHECK("type" <> 'Journal' OR "objective" IS NOT NULL),
	CONSTRAINT "nodes_journal_work_summary_required" CHECK("type" <> 'Journal' OR "work_summary" IS NOT NULL),
	CONSTRAINT "nodes_journal_handover_required" CHECK("type" <> 'Journal' OR "handover" IS NOT NULL),
	CONSTRAINT "nodes_worklog_narrative_required" CHECK("type" <> 'WorkLog' OR "narrative" IS NOT NULL),
	CONSTRAINT "nodes_worklog_outcome_required" CHECK("type" <> 'WorkLog' OR "outcome" IS NOT NULL),
	CONSTRAINT "nodes_evidence_claim_required" CHECK("type" <> 'Evidence' OR "claim" IS NOT NULL),
	CONSTRAINT "nodes_evidence_verdict_required" CHECK("type" <> 'Evidence' OR "verdict" IS NOT NULL),
	CONSTRAINT "nodes_commit_sha_required" CHECK("type" <> 'Commit' OR "sha" IS NOT NULL),
	CONSTRAINT "nodes_verificationreport_testimony_required" CHECK("type" <> 'VerificationReport' OR "testimony" IS NOT NULL),
	CONSTRAINT "nodes_verificationreport_coverage_required" CHECK("type" <> 'VerificationReport' OR "coverage" IS NOT NULL),
	CONSTRAINT "nodes_verificationreport_trigger_required" CHECK("type" <> 'VerificationReport' OR "trigger" IS NOT NULL),
	CONSTRAINT "nodes_finding_statement_required" CHECK("type" <> 'Finding' OR "statement" IS NOT NULL),
	CONSTRAINT "nodes_finding_description_required" CHECK("type" <> 'Finding' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_finding_finding_type_required" CHECK("type" <> 'Finding' OR "finding_type" IS NOT NULL),
	CONSTRAINT "nodes_assumption_statement_required" CHECK("type" <> 'Assumption' OR "statement" IS NOT NULL),
	CONSTRAINT "nodes_assumption_description_required" CHECK("type" <> 'Assumption' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_question_question_required" CHECK("type" <> 'Question' OR "question" IS NOT NULL),
	CONSTRAINT "nodes_question_description_required" CHECK("type" <> 'Question' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_question_state_required" CHECK("type" <> 'Question' OR "state" IS NOT NULL),
	CONSTRAINT "nodes_decision_decision_required" CHECK("type" <> 'Decision' OR "decision" IS NOT NULL),
	CONSTRAINT "nodes_decision_description_required" CHECK("type" <> 'Decision' OR "description" IS NOT NULL),
	CONSTRAINT "nodes_decision_rationale_required" CHECK("type" <> 'Decision' OR "rationale" IS NOT NULL),
	CONSTRAINT "nodes_aliases_prose_text" CHECK("aliases" IS NULL OR ("aliases" <> '' AND trim("aliases") = "aliases" AND octet_length("aliases") <= 262144)),
	CONSTRAINT "nodes_answer_prose_text" CHECK("answer" IS NULL OR ("answer" <> '' AND trim("answer") = "answer" AND octet_length("answer") <= 262144)),
	CONSTRAINT "nodes_applies_when_line_text" CHECK("applies_when" IS NULL OR ("applies_when" <> '' AND trim("applies_when") = "applies_when" AND octet_length("applies_when") <= 262144 AND instr("applies_when", char(10)) = 0 AND instr("applies_when", char(13)) = 0)),
	CONSTRAINT "nodes_basis_prose_text" CHECK("basis" IS NULL OR ("basis" <> '' AND trim("basis") = "basis" AND octet_length("basis") <= 262144)),
	CONSTRAINT "nodes_behavior_design_description_prose_text" CHECK("behavior_design_description" IS NULL OR ("behavior_design_description" <> '' AND trim("behavior_design_description") = "behavior_design_description" AND octet_length("behavior_design_description") <= 262144)),
	CONSTRAINT "nodes_benchmark_prose_text" CHECK("benchmark" IS NULL OR ("benchmark" <> '' AND trim("benchmark") = "benchmark" AND octet_length("benchmark") <= 262144)),
	CONSTRAINT "nodes_benefit_line_text" CHECK("benefit" IS NULL OR ("benefit" <> '' AND trim("benefit") = "benefit" AND octet_length("benefit") <= 262144 AND instr("benefit", char(10)) = 0 AND instr("benefit", char(13)) = 0)),
	CONSTRAINT "nodes_claim_prose_text" CHECK("claim" IS NULL OR ("claim" <> '' AND trim("claim") = "claim" AND octet_length("claim") <= 262144)),
	CONSTRAINT "nodes_contract_description_prose_text" CHECK("contract_description" IS NULL OR ("contract_description" <> '' AND trim("contract_description") = "contract_description" AND octet_length("contract_description") <= 262144)),
	CONSTRAINT "nodes_coverage_prose_text" CHECK("coverage" IS NULL OR ("coverage" <> '' AND trim("coverage") = "coverage" AND octet_length("coverage") <= 262144)),
	CONSTRAINT "nodes_decision_prose_text" CHECK("decision" IS NULL OR ("decision" <> '' AND trim("decision") = "decision" AND octet_length("decision") <= 262144)),
	CONSTRAINT "nodes_definition_prose_text" CHECK("definition" IS NULL OR ("definition" <> '' AND trim("definition") = "definition" AND octet_length("definition") <= 262144)),
	CONSTRAINT "nodes_definition_of_done_prose_text" CHECK("definition_of_done" IS NULL OR ("definition_of_done" <> '' AND trim("definition_of_done") = "definition_of_done" AND octet_length("definition_of_done") <= 262144)),
	CONSTRAINT "nodes_deliverables_prose_text" CHECK("deliverables" IS NULL OR ("deliverables" <> '' AND trim("deliverables") = "deliverables" AND octet_length("deliverables") <= 262144)),
	CONSTRAINT "nodes_description_prose_text" CHECK("description" IS NULL OR ("description" <> '' AND trim("description") = "description" AND octet_length("description") <= 262144)),
	CONSTRAINT "nodes_evaluation_process_prose_text" CHECK("evaluation_process" IS NULL OR ("evaluation_process" <> '' AND trim("evaluation_process") = "evaluation_process" AND octet_length("evaluation_process") <= 262144)),
	CONSTRAINT "nodes_goal_prose_text" CHECK("goal" IS NULL OR ("goal" <> '' AND trim("goal") = "goal" AND octet_length("goal") <= 262144)),
	CONSTRAINT "nodes_handover_prose_text" CHECK("handover" IS NULL OR ("handover" <> '' AND trim("handover") = "handover" AND octet_length("handover") <= 262144)),
	CONSTRAINT "nodes_key_attributes_prose_text" CHECK("key_attributes" IS NULL OR ("key_attributes" <> '' AND trim("key_attributes") = "key_attributes" AND octet_length("key_attributes") <= 262144)),
	CONSTRAINT "nodes_message_prose_text" CHECK("message" IS NULL OR ("message" <> '' AND trim("message") = "message" AND octet_length("message") <= 262144)),
	CONSTRAINT "nodes_narrative_prose_text" CHECK("narrative" IS NULL OR ("narrative" <> '' AND trim("narrative") = "narrative" AND octet_length("narrative") <= 262144)),
	CONSTRAINT "nodes_non_goals_prose_text" CHECK("non_goals" IS NULL OR ("non_goals" <> '' AND trim("non_goals") = "non_goals" AND octet_length("non_goals") <= 262144)),
	CONSTRAINT "nodes_objective_prose_text" CHECK("objective" IS NULL OR ("objective" <> '' AND trim("objective") = "objective" AND octet_length("objective") <= 262144)),
	CONSTRAINT "nodes_outcome_prose_text" CHECK("outcome" IS NULL OR ("outcome" <> '' AND trim("outcome") = "outcome" AND octet_length("outcome") <= 262144)),
	CONSTRAINT "nodes_performer_line_text" CHECK("performer" IS NULL OR ("performer" <> '' AND trim("performer") = "performer" AND octet_length("performer") <= 262144 AND instr("performer", char(10)) = 0 AND instr("performer", char(13)) = 0)),
	CONSTRAINT "nodes_period_line_text" CHECK("period" IS NULL OR ("period" <> '' AND trim("period") = "period" AND octet_length("period") <= 262144 AND instr("period", char(10)) = 0 AND instr("period", char(13)) = 0)),
	CONSTRAINT "nodes_postconditions_prose_text" CHECK("postconditions" IS NULL OR ("postconditions" <> '' AND trim("postconditions") = "postconditions" AND octet_length("postconditions") <= 262144)),
	CONSTRAINT "nodes_preconditions_prose_text" CHECK("preconditions" IS NULL OR ("preconditions" <> '' AND trim("preconditions") = "preconditions" AND octet_length("preconditions") <= 262144)),
	CONSTRAINT "nodes_protocol_line_text" CHECK("protocol" IS NULL OR ("protocol" <> '' AND trim("protocol") = "protocol" AND octet_length("protocol") <= 262144 AND instr("protocol", char(10)) = 0 AND instr("protocol", char(13)) = 0)),
	CONSTRAINT "nodes_question_line_text" CHECK("question" IS NULL OR ("question" <> '' AND trim("question") = "question" AND octet_length("question") <= 262144 AND instr("question", char(10)) = 0 AND instr("question", char(13)) = 0)),
	CONSTRAINT "nodes_rationale_prose_text" CHECK("rationale" IS NULL OR ("rationale" <> '' AND trim("rationale") = "rationale" AND octet_length("rationale") <= 262144)),
	CONSTRAINT "nodes_risks_prose_text" CHECK("risks" IS NULL OR ("risks" <> '' AND trim("risks") = "risks" AND octet_length("risks") <= 262144)),
	CONSTRAINT "nodes_role_description_prose_text" CHECK("role_description" IS NULL OR ("role_description" <> '' AND trim("role_description") = "role_description" AND octet_length("role_description") <= 262144)),
	CONSTRAINT "nodes_scope_prose_text" CHECK("scope" IS NULL OR ("scope" <> '' AND trim("scope") = "scope" AND octet_length("scope") <= 262144)),
	CONSTRAINT "nodes_sha_line_text" CHECK("sha" IS NULL OR ("sha" <> '' AND trim("sha") = "sha" AND octet_length("sha") <= 262144 AND instr("sha", char(10)) = 0 AND instr("sha", char(13)) = 0)),
	CONSTRAINT "nodes_statement_line_text" CHECK("statement" IS NULL OR ("statement" <> '' AND trim("statement") = "statement" AND octet_length("statement") <= 262144 AND instr("statement", char(10)) = 0 AND instr("statement", char(13)) = 0)),
	CONSTRAINT "nodes_steps_prose_text" CHECK("steps" IS NULL OR ("steps" <> '' AND trim("steps") = "steps" AND octet_length("steps") <= 262144)),
	CONSTRAINT "nodes_structural_design_description_prose_text" CHECK("structural_design_description" IS NULL OR ("structural_design_description" <> '' AND trim("structural_design_description") = "structural_design_description" AND octet_length("structural_design_description") <= 262144)),
	CONSTRAINT "nodes_success_measure_prose_text" CHECK("success_measure" IS NULL OR ("success_measure" <> '' AND trim("success_measure") = "success_measure" AND octet_length("success_measure") <= 262144)),
	CONSTRAINT "nodes_testimony_prose_text" CHECK("testimony" IS NULL OR ("testimony" <> '' AND trim("testimony") = "testimony" AND octet_length("testimony") <= 262144)),
	CONSTRAINT "nodes_trigger_prose_text" CHECK("trigger" IS NULL OR ("trigger" <> '' AND trim("trigger") = "trigger" AND octet_length("trigger") <= 262144)),
	CONSTRAINT "nodes_work_summary_prose_text" CHECK("work_summary" IS NULL OR ("work_summary" <> '' AND trim("work_summary") = "work_summary" AND octet_length("work_summary") <= 262144))
);
--> statement-breakpoint
INSERT INTO `__new_nodes`("id", "type", "short_name", "name", "actor_type", "aliases", "answer", "applies_when", "basis", "behavior_design_description", "benchmark", "benefit", "claim", "constraint_type", "contract_description", "coverage", "decision", "definition", "definition_of_done", "deliverables", "description", "evaluation_process", "finding_type", "goal", "handover", "interface_type", "key_attributes", "message", "narrative", "non_goals", "objective", "outcome", "performer", "period", "postconditions", "preconditions", "priority", "protocol", "question", "rationale", "requirement_type", "responsibility_type", "risks", "role_description", "scenario_type", "scope", "severity", "sha", "state", "statement", "steps", "structural_design_description", "success_measure", "testimony", "trigger", "verdict", "work_summary", "created_at", "updated_at")
SELECT
	"id",
	"type",
	CASE WHEN trim("short_name") = '' THEN 'test text' ELSE trim("short_name") END AS "short_name",
	CASE WHEN trim("name") = '' THEN 'test text' ELSE trim("name") END AS "name",
	CASE WHEN "type" IN ('Actor') THEN 'user' END AS "actor_type",
	NULL AS "aliases",
	NULL AS "answer",
	NULL AS "applies_when",
	NULL AS "basis",
	CASE WHEN "type" IN ('ModuleDesign') THEN 'test text' END AS "behavior_design_description",
	NULL AS "benchmark",
	CASE WHEN "type" IN ('UseCase') THEN 'test text' END AS "benefit",
	CASE WHEN "type" IN ('Evidence') THEN 'test text' END AS "claim",
	CASE WHEN "type" IN ('Constraint') THEN 'platform' END AS "constraint_type",
	CASE WHEN "type" IN ('Interface') THEN 'test text' END AS "contract_description",
	CASE WHEN "type" IN ('VerificationReport') THEN 'test text' END AS "coverage",
	CASE WHEN "type" IN ('Decision') THEN 'test text' END AS "decision",
	CASE WHEN "type" IN ('Term') THEN 'test text' END AS "definition",
	CASE WHEN "type" IN ('ImplementationTask') THEN 'test text' END AS "definition_of_done",
	CASE WHEN "type" IN ('ImplementationTask') THEN 'test text' END AS "deliverables",
	CASE WHEN "type" IN ('DomainEntity', 'Actor', 'UseCase', 'SystemResponsibility', 'Requirement', 'AcceptanceCriterion', 'Constraint', 'DataSchema', 'ImplementationTask', 'Finding', 'Assumption', 'Question', 'Decision') THEN 'test text' END AS "description",
	CASE WHEN "type" IN ('AcceptanceCriterion') THEN 'test text' END AS "evaluation_process",
	CASE WHEN "type" IN ('Finding') THEN 'missing' END AS "finding_type",
	CASE WHEN "type" IN ('ImplementationTask') THEN 'test text' END AS "goal",
	CASE WHEN "type" IN ('Journal') THEN 'test text' END AS "handover",
	CASE WHEN "type" IN ('Interface') THEN 'api' END AS "interface_type",
	NULL AS "key_attributes",
	NULL AS "message",
	CASE WHEN "type" IN ('WorkLog') THEN 'test text' END AS "narrative",
	NULL AS "non_goals",
	CASE WHEN "type" IN ('Journal') THEN 'test text' END AS "objective",
	CASE WHEN "type" IN ('WorkLog') THEN 'test text' END AS "outcome",
	CASE WHEN "type" IN ('Journal') THEN 'test text' END AS "performer",
	CASE WHEN "type" IN ('Journal') THEN 'test text' END AS "period",
	CASE WHEN "type" IN ('Scenario') THEN 'test text' END AS "postconditions",
	CASE WHEN "type" IN ('Scenario') THEN 'test text' END AS "preconditions",
	CASE WHEN "type" IN ('UseCase', 'Requirement') THEN 'high' END AS "priority",
	NULL AS "protocol",
	CASE WHEN "type" IN ('Question') THEN 'test text' END AS "question",
	CASE WHEN "type" IN ('Decision') THEN 'test text' END AS "rationale",
	CASE WHEN "type" IN ('Requirement') THEN 'functional' END AS "requirement_type",
	CASE WHEN "type" IN ('SystemResponsibility') THEN 'core' END AS "responsibility_type",
	NULL AS "risks",
	CASE WHEN "type" IN ('ModuleDesign') THEN 'test text' END AS "role_description",
	CASE WHEN "type" IN ('Scenario') THEN 'main' END AS "scenario_type",
	CASE WHEN "type" IN ('ImplementationTask') THEN 'test text' END AS "scope",
	NULL AS "severity",
	CASE WHEN "type" IN ('Commit') THEN 'test text' END AS "sha",
	CASE WHEN "type" IN ('Question') THEN 'open' END AS "state",
	CASE WHEN "type" IN ('Goal', 'SystemResponsibility', 'Requirement', 'AcceptanceCriterion', 'Constraint', 'Finding', 'Assumption') THEN 'test text' END AS "statement",
	CASE WHEN "type" IN ('Scenario') THEN 'test text' END AS "steps",
	CASE WHEN "type" IN ('ModuleDesign') THEN 'test text' END AS "structural_design_description",
	NULL AS "success_measure",
	CASE WHEN "type" IN ('VerificationReport') THEN 'test text' END AS "testimony",
	CASE WHEN "type" IN ('VerificationReport') THEN 'test text' END AS "trigger",
	CASE WHEN "type" IN ('Evidence') THEN 'pending' END AS "verdict",
	CASE WHEN "type" IN ('Journal') THEN 'test text' END AS "work_summary",
	"created_at",
	"updated_at"
FROM `nodes` WHERE `type` IN ('Term', 'DomainEntity', 'Goal', 'Actor', 'UseCase', 'Scenario', 'SystemResponsibility', 'Requirement', 'AcceptanceCriterion', 'Constraint', 'ModuleDesign', 'Interface', 'DataSchema', 'ImplementationTask', 'Journal', 'WorkLog', 'Evidence', 'Commit', 'VerificationReport', 'Finding', 'Assumption', 'Question', 'Decision');
--> statement-breakpoint
DROP TABLE `nodes`;
--> statement-breakpoint
ALTER TABLE `__new_nodes` RENAME TO `nodes`;
--> statement-breakpoint
CREATE TABLE `__new_edges` (
	`id` text PRIMARY KEY NOT NULL,
	`type` text NOT NULL,
	`from_id` text NOT NULL,
	`to_id` text NOT NULL,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`from_id`) REFERENCES `nodes`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`to_id`) REFERENCES `nodes`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "edges_no_self_reference" CHECK("from_id" <> "to_id")
);
--> statement-breakpoint
INSERT INTO `__new_edges`("id", "type", "from_id", "to_id", "created_at")
SELECT "id", "type", "from_id", "to_id", "created_at" FROM `edges` AS `edge`
WHERE `edge`.`from_id` <> `edge`.`to_id`
	AND EXISTS (SELECT 1 FROM `nodes` WHERE `nodes`.`id` = `edge`.`from_id`)
	AND EXISTS (SELECT 1 FROM `nodes` WHERE `nodes`.`id` = `edge`.`to_id`)
	AND `edge`.`id` = (SELECT min(`id`) FROM `edges` AS `same` WHERE `same`.`from_id` = `edge`.`from_id` AND `same`.`type` = `edge`.`type` AND `same`.`to_id` = `edge`.`to_id`);
--> statement-breakpoint
DROP TABLE `edges`;
--> statement-breakpoint
ALTER TABLE `__new_edges` RENAME TO `edges`;
--> statement-breakpoint
CREATE UNIQUE INDEX `edges_one_relation_per_triple` ON `edges` (`from_id`,`type`,`to_id`);
