import assert from "node:assert/strict";
import { chmod, mkdir, mkdtemp, readFile, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, test } from "node:test";
import { AGENT_RULES_FILE, writeAgentRules } from "./agent-rules.js";

/**
 * The page Shall writes into a project's `.claude/rules`.
 *
 * WHAT IS PINNED HERE IS OWNERSHIP, and it is the opposite of the settings file
 * next door: that one is somebody's document Shall adds two lines to, this one
 * is Shall's output living in somebody's folder. So the tests are that it
 * arrives, that it is rewritten when it has drifted, that an open which changes
 * nothing leaves the mtime alone — a `git status` full of untouched files is
 * how a generated page wears out its welcome — and that a folder Shall cannot
 * write to is not an error worth failing an open over.
 */

async function newProject(): Promise<string> {
  return mkdtemp(path.join(os.tmpdir(), "shall-agent-rules-"));
}

function rulesPathOf(projectPath: string): string {
  return path.join(projectPath, ...AGENT_RULES_FILE.split("/"));
}

describe("the rules page", () => {
  test("a project with no page gets one", async () => {
    const project = await newProject();
    await writeAgentRules(project);

    const text = await readFile(rulesPathOf(project), "utf8");
    assert.ok(text.startsWith("<!-- Generated by Shall"), text.slice(0, 80));
    // The four sentences an agent must not get wrong, whatever else the page
    // grows: what a write is, what a delete is, who may read the books, and
    // the one seam nothing downstream will ever report.
    assert.match(text, /Writing a spec file is a proposal/);
    assert.match(text, /Never delete a spec file/);
    assert.match(text, /Never open `\.shall\/ledger\/`/);
    assert.match(text, /A work item hangs off a module/);
    // And the one line that is not a rule: where the processes are, all four
    // of them, and the guide for when the thread is lost. An agent that never
    // learns the work commands exist writes the execution record by hand,
    // which is what they were built to stop.
    assert.match(text, /\/shall:specify/);
    assert.match(text, /\/shall:plan/);
    assert.match(text, /\/shall:work/);
    assert.match(text, /\/shall:raise/);
    assert.match(text, /\/shall:help/);
    // The one write under the ledger folder an agent is meant to ask for, named
    // beside the rule that forbids the rest — so the page that says "never open
    // the ledger" is the page that says how the feed's one line gets there.
    assert.match(text, /shall log/);
    assert.ok(text.endsWith("\n"), JSON.stringify(text.slice(-40)));
  });

  test("writing it twice leaves the second write undone", async () => {
    const project = await newProject();
    await writeAgentRules(project);
    const first = await stat(rulesPathOf(project));

    await writeAgentRules(project);
    const second = await stat(rulesPathOf(project));

    assert.equal(second.mtimeMs, first.mtimeMs);
    assert.equal(second.ino, first.ino);
  });

  test("a page from an older Shall is replaced whole", async () => {
    const project = await newProject();
    const target = rulesPathOf(project);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, "# Shall\n\nSomething an older Shall said.\n", "utf8");

    await writeAgentRules(project);

    const text = await readFile(target, "utf8");
    assert.doesNotMatch(text, /Something an older Shall said/);
    assert.match(text, /Never delete a spec file/);
  });

  test("a folder it cannot write to is not an error", async () => {
    const project = await newProject();
    const claude = path.join(project, ".claude");
    await mkdir(claude, { recursive: true });
    await chmod(claude, 0o500);
    try {
      await writeAgentRules(project);
    } finally {
      await chmod(claude, 0o700);
    }
    // Nothing thrown, and nothing written: an open goes ahead either way.
    await assert.rejects(readFile(rulesPathOf(project), "utf8"));
  });

  test("it leaves the rest of the folder alone", async () => {
    const project = await newProject();
    const mine = path.join(project, ".claude", "rules", "testing.md");
    await mkdir(path.dirname(mine), { recursive: true });
    await writeFile(mine, "# Testing\n\nRun the suite before pushing.\n", "utf8");

    await writeAgentRules(project);

    assert.equal(
      await readFile(mine, "utf8"),
      "# Testing\n\nRun the suite before pushing.\n",
    );
  });
});
