import { mkdir, readFile } from "node:fs/promises";
import path from "node:path";
import { writeByRename } from "./atomic-write.js";

/**
 * The page every agent working in this project reads before it does anything —
 * half a page of rules that are not discoverable from the files themselves.
 *
 * WHY IT IS ITS OWN FILE AND NOT A PARAGRAPH IN SOMEBODY'S CLAUDE.md. A project
 * already has an instructions file, usually a long one, and appending to it
 * puts Shall's rules wherever the append landed — under someone else's heading,
 * below three hundred lines about the build, and at the mercy of the next
 * person who reorganises the page. `.claude/rules/*.md` is loaded into every
 * session exactly as the instructions file is, with the same standing, and a
 * file of Shall's own can be regenerated without reading anybody's prose.
 *
 * SHALL OWNS THIS FILE WHOLE. It is written on create and brought current on
 * every open, the way the reference templates are, and a hand edit is lost on
 * the next open — which is said in the file's first line. That is the opposite
 * of the settings file next door, where Shall merges two array entries into
 * somebody else's document and touches nothing else: this page is generated
 * output, that one is a person's file with two lines of ours in it.
 *
 * IT IS THE FIRST OF THE THREE LAYERS. This is what is true in every session;
 * how to write a node is the `shall-authoring` skill, and how to elicit a
 * specification is `/shall:specify`. The rules that must not be broken live
 * here because the layers below are loaded only when something asks for them,
 * and an agent that never opens a skill still must not delete a spec file.
 *
 * Only the Claude adapter exists today, which is why this lands under
 * `.claude`. An agent that reads AGENTS.md is not covered yet.
 */
const RULES = `<!-- Generated by Shall, and rewritten whenever this project is opened. Put your own rules in another file under .claude/rules/. -->

# Shall

This project's specification is a graph of markdown files, and Shall is what
reads and judges them.

\`\`\`
.shall/spec/<band>/<Type>/<id>.md   one file per node: the folder is its type, the filename its id
.shall/ledger/*.yaml                approvals, rejections, closures — Shall's own books
\`\`\`

**Writing a spec file is a proposal.** A node you write or change is yellow
until a person approves it in the browser, and changing an approved node turns
it yellow again — which costs somebody a second reading, so change what you
mean to change and say why.

**Never delete a spec file.** Add a \`deletionProposed\` block carrying \`by\` and
\`rationale\` to its frontmatter and leave the file where it is. A person decides.

**Never open \`.shall/ledger/\`.** Writing there is refused outright, and reading
it will not tell you a colour: a colour is arithmetic over all three books and
the current bytes of every file. Ask instead.

**Ask; do not work it out.** \`shall status\` gives every node's colour, why it is
that colour, and any rejection's rationale in full. \`shall board\` gives what is
red and what is ready to start. \`shall check\` is the compiler — it exits 1 while
the graph does not hold together. Never reason out a colour or a readiness
yourself; you will disagree with the screen.

**Start a node with \`shall add-spec-node --type <Type>\`.** It writes the file at
its own path with the next free id, and its commented header is the only place
that says which relations that type may draw and what its body might hold. A
relation is written in the file it LEAVES, so anchoring a new child means
editing the child's parent.

Approving, rejecting and closing are a person's, made in the browser: \`shall\`
with no arguments opens it. There is no \`shall approve\`.

Working on the specification itself? \`/shall:specify\` runs the elicitation and
the \`shall-authoring\` skill carries the rest, when the Shall plugin is loaded.
`;

/** Where the page lives, as a project-relative path for anyone reporting it. */
export const AGENT_RULES_FILE = ".claude/rules/shall.md";

function agentRulesPath(projectPath: string): string {
  return path.join(projectPath, ".claude", "rules", "shall.md");
}

/**
 * Writes the page, and rewrites it only when the bytes differ.
 *
 * IT NEVER THROWS, for the reason its neighbour does not: this is an open-time
 * convenience and not a condition of opening a project. A read-only checkout, a
 * `.claude` folder owned by another user, a filesystem that is full — none of
 * them is a reason a person cannot open their project and read their own graph.
 *
 * Comparing before writing keeps the mtime quiet when there is nothing to do,
 * so an open that changes nothing shows up in nobody's `git status`.
 */
export async function writeAgentRules(projectPath: string): Promise<void> {
  try {
    const target = agentRulesPath(projectPath);
    if ((await readFile(target, "utf8").catch(() => null)) === RULES) {
      return;
    }
    await mkdir(path.dirname(target), { recursive: true });
    await writeByRename(target, RULES);
  } catch {
    // Silence, deliberately: see above.
  }
}
