import { mkdir, readdir, readFile, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SHALL_VERSION } from "@shall/core/version";
import { writeByRename } from "./atomic-write.js";
import type { KitLayout } from "./adapters/adapter.js";
import { getAgentSettingsPath } from "./agent-settings.js";
import { isEmbedded, listEmbedded, readEmbeddedText } from "./embedded.js";

/**
 * THE AGENT KIT: the generated commands, skills and compile hook, written into
 * a project's own folder so that being a Shall project IS being wired — no
 * install step, no `--plugin-dir`, no second procedure. `shall init` writes the
 * kit and every open rewrites whatever drifted, exactly as the rules page and
 * the deny rules are handled next door.
 *
 * THE GENERATED TREE STAYS THE ONE SOURCE. Nothing here is a second copy of the
 * process prose: the kit is read out of the repository's `agents/dist/<agent>/`
 * folder at write time and transformed for the dialect the project speaks. For
 * Claude that is the project-command dialect — the colon namespace is the plugin
 * form and a project command cannot wear it, so `/shall:specify` becomes
 * `/shall.specify`, a skill is called by its bare name, and the hook runs from
 * the project's own folder. The generated folder stays the source of the text;
 * the kit is that text in the project's grammar.
 *
 * WHAT IS AN AGENT'S IS IN ITS LAYOUT AND NOWHERE ELSE. This file holds the
 * machinery every kit is written by — the marker, the version stamp, the
 * byte-quiet write, the marker-guarded removal, the hook merge — and a
 * `KitLayout` says where one agent's files come from, where they land, what
 * dialect they are said in, and which of its own files are inputs rather than
 * copies. Adding an agent adds a layout and an adapter; it does not add a
 * branch here.
 *
 * EVERY GENERATED FILE CARRIES THE MARKER, and the marker is the ownership
 * test: stale `shall.*` commands and `shall-*` skills are removed only when
 * they carry it, so a person's own file that happens to share the prefix is
 * never Shall's to delete. THE MARKER'S OWN WORDS NEVER MOVE — a kit written
 * by an older Shall has to go on matching, or the day it is upgraded is the day
 * its files stop being Shall's and are left behind for ever.
 *
 * UNDER THE MARKER SITS THE VERSION THAT WROTE THE FILE, which is what makes an
 * upgrade visible: the write below compares bytes, and a moved version moves
 * every file in the kit, so a project opened by a new Shall is regenerated
 * whole rather than left carrying last release's prose.
 *
 * IT NEVER THROWS, for the reason its neighbours do not: wiring is an
 * open-time convenience, not a condition of opening a project.
 */

const moduleDirectory = path.dirname(fileURLToPath(import.meta.url));

/**
 * One agent's generated folder in the checkout this daemon runs from — src and
 * dist sit at the same depth.
 *
 * IT IS GENERATED, NOT WRITTEN. `scripts/build-agents.mjs` multiplies
 * `agents/core` by `agents/profiles/<agent>` into these folders, so a checkout
 * that has never run `bun run build:agents` has nothing there — which is why
 * the root build and test chains run it first, and why writing the kit is
 * allowed to fail quietly.
 *
 * A SINGLE-BINARY SHALL HAS NO CHECKOUT BEHIND IT, so it carries the same
 * folders as bytes and the walk below reads those instead. What is carried is
 * what the walk would have found, which is why the two sources can share every
 * line after them.
 */
export function generatedRoot(agent: string): string {
  return path.resolve(moduleDirectory, "..", "..", "..", "agents", "dist", agent);
}

/**
 * The one line that marks a generated file as Shall's to rewrite and to remove.
 *
 * ITS BYTES ARE FROZEN. Ownership is tested by this exact string, and every kit
 * any Shall ever wrote carries it — so the version that wrote a file is said on
 * the line below rather than in here, where a new word would orphan every kit
 * older than it.
 */
export const KIT_MARKER =
  "<!-- Generated by Shall from its plugin. Rewritten whenever this project is opened; edits here are overwritten. -->";

/** Which Shall wrote the file — the second line of every marked one. */
export const KIT_VERSION_LINE = `<!-- Version: ${SHALL_VERSION} -->`;

/**
 * The plugin dialect, said in the project's grammar — Claude's, where a project
 * command cannot wear the plugin's colon namespace. Order matters — the
 * namespaced skill specifier is rewritten before the command names — and the
 * leading slash on the command pattern keeps `Bash(shall:*)` untouched.
 */
function claudeDialect(text: string): string {
  return text
    .replaceAll("shall:shall-", "shall-")
    .replaceAll("/shall:", "/shall.")
    .replaceAll("${CLAUDE_PLUGIN_ROOT}/skills/", ".claude/skills/")
    .replaceAll("${CLAUDE_PLUGIN_ROOT}/hooks/", ".claude/hooks/shall/");
}

/** The marker and the version under it, seated after the frontmatter where there is one, so the frontmatter stays first. */
export function withMarker(text: string): string {
  const head = `${KIT_MARKER}\n${KIT_VERSION_LINE}`;
  if (text.startsWith("---\n")) {
    const close = text.indexOf("\n---\n", 4);
    if (close !== -1) {
      const at = close + "\n---\n".length;
      return `${text.slice(0, at)}\n${head}\n${text.slice(at)}`;
    }
  }
  return `${head}\n\n${text}`;
}

interface KitFile {
  /** Project-relative target, "/"-separated. */
  readonly to: string;
  readonly content: string;
}

/**
 * Where a Claude plugin file lands in a project, or null when it is not part of
 * the kit. THE THREE SHAPES ARE THE WHOLE KIT: a command is renamed into the
 * project-command dialect, a skill arrives whole under its own name, and the
 * hook is the one file that is script rather than prose and so carries no
 * marker — a comment in it would be read by node, not by Claude.
 */
function claudeTargetOf(relative: string): string | null {
  const [folder, ...rest] = relative.split("/");
  if (folder === "commands" && rest.length === 1 && relative.endsWith(".md")) {
    return `.claude/commands/shall.${rest.join("/")}`;
  }
  if (folder === "skills" && rest.length > 1 && relative.endsWith(".md")) {
    return `.claude/skills/${rest.join("/")}`;
  }
  if (relative === "hooks/check-spec.mjs") {
    return ".claude/hooks/shall/check-spec.mjs";
  }
  return null;
}

/** Every file of the Claude tree, "/"-separated from its root, in walk order. */
async function claudeWalk(root: string): Promise<string[]> {
  const found: string[] = [];
  for (const entry of await readdir(path.join(root, "commands"))) {
    found.push(`commands/${entry}`);
  }
  found.push(...(await skillFiles(root)));
  found.push("hooks/check-spec.mjs");
  return found;
}

/** Every `.md` under a tree's `skills/`, "/"-separated from the tree's root. */
export async function skillFiles(root: string): Promise<string[]> {
  const found: string[] = [];
  const skillsRoot = path.join(root, "skills");
  for (const skill of await readdir(skillsRoot)) {
    for (const relative of await markdownUnder(path.join(skillsRoot, skill))) {
      found.push(`skills/${skill}/${relative}`);
    }
  }
  return found;
}

/** Every `.md` under a folder, as "/"-separated relative paths, in walk order. */
export async function markdownUnder(
  folder: string,
  prefix = "",
): Promise<string[]> {
  const found: string[] = [];
  for (const entry of await readdir(folder, { withFileTypes: true })) {
    const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      found.push(
        ...(await markdownUnder(path.join(folder, entry.name), relative)),
      );
    } else if (entry.name.endsWith(".md")) {
      found.push(relative);
    }
  }
  return found;
}

/** Every file of one agent's tree, from the checkout or from the bytes carried. */
async function treeFiles(layout: KitLayout): Promise<string[]> {
  if (isEmbedded()) {
    return listEmbedded(layout.embeddedPrefix);
  }
  return layout.walk(layout.root());
}

/**
 * One generated file's text, from the checkout or from the bytes carried.
 *
 * IT IS ALSO HOW THE FILES THAT ARE NOT COPIED ARE READ. A layout's `targetOf`
 * refuses the two Codex carries as inputs — the hook wiring and the always-on
 * `AGENTS.md` block — and the adapter reads them by name through here, so that
 * a binary and a checkout answer the same way for them too.
 */
export async function readKitFile(
  layout: KitLayout,
  relative: string,
): Promise<string> {
  if (isEmbedded()) {
    const text = readEmbeddedText(`${layout.embeddedPrefix}${relative}`);
    if (text === undefined) {
      throw new Error(`Shall carries no ${layout.agent} file at ${relative}`);
    }
    return text;
  }
  return readFile(path.join(layout.root(), ...relative.split("/")), "utf8");
}

/** Every file of the kit, read fresh from the generated tree and transformed. */
async function kitOf(layout: KitLayout): Promise<KitFile[]> {
  const files: KitFile[] = [];
  for (const relative of await treeFiles(layout)) {
    const to = layout.targetOf(relative);
    if (to === null) {
      continue;
    }
    const text = await readKitFile(layout, relative);
    files.push({
      to,
      content: to.endsWith(".mjs") ? text : withMarker(layout.transform(text)),
    });
  }
  return files;
}

/** Writes one file when its bytes differ, making the folders it needs. */
export async function writeIfChanged(
  target: string,
  content: string,
): Promise<void> {
  if ((await readFile(target, "utf8").catch(() => null)) === content) {
    return;
  }
  await mkdir(path.dirname(target), { recursive: true });
  await writeByRename(target, content);
}

/** Removes a folder of an earlier layout, file by marker-guarded file, then the folder when empty. */
export async function removeMarkedFolder(folder: string): Promise<void> {
  for (const entry of await readdir(folder).catch(() => [])) {
    const text = await readFile(path.join(folder, entry), "utf8").catch(() => "");
    if (text.includes(KIT_MARKER)) {
      await rm(path.join(folder, entry), { force: true });
    }
  }
  if ((await readdir(folder).catch(() => ["x"])).length === 0) {
    await rm(folder, { recursive: true, force: true });
  }
}

/**
 * The `shall-*` skill folders an older kit left behind, removed — marker-guarded
 * on the skill's own page, so a person's skill that happens to share the prefix,
 * and a folder with no page in it at all, are never Shall's to delete.
 *
 * The skills root is the layout's, because the two agents keep their skills in
 * different folders and the sweep is otherwise the same sweep.
 */
export async function removeStaleSkills(
  projectPath: string,
  written: ReadonlySet<string>,
  skillsRelative: string,
): Promise<void> {
  const skillsDir = path.join(projectPath, ...skillsRelative.split("/"));
  const owned = new Set(
    [...written]
      .filter((held) => held.startsWith(`${skillsRelative}/`))
      .map((held) => held.split("/")[2] ?? ""),
  );
  for (const entry of await readdir(skillsDir).catch(() => [])) {
    if (!entry.startsWith("shall-") || owned.has(entry)) {
      continue;
    }
    const page = await readFile(
      path.join(skillsDir, entry, "SKILL.md"),
      "utf8",
    ).catch(() => "");
    if (page.includes(KIT_MARKER)) {
      await rm(path.join(skillsDir, entry), { recursive: true, force: true });
    }
  }
}

/** Removes the Claude kit files an older kit wrote and this one no longer carries. */
async function claudeRemoveStale(
  projectPath: string,
  written: ReadonlySet<string>,
): Promise<void> {
  const commandsDir = path.join(projectPath, ".claude", "commands");
  for (const entry of await readdir(commandsDir).catch(() => [])) {
    const relative = `.claude/commands/${entry}`;
    if (
      !(entry.startsWith("shall.") || entry.startsWith("shall/")) &&
      entry !== "shall"
    ) {
      continue;
    }
    if (entry === "shall") {
      // The folder an earlier layout wrote; its files carry the marker.
      await removeMarkedFolder(path.join(commandsDir, entry));
      continue;
    }
    if (!entry.endsWith(".md") || written.has(relative)) {
      continue;
    }
    const text = await readFile(path.join(commandsDir, entry), "utf8").catch(
      () => "",
    );
    if (text.includes(KIT_MARKER)) {
      await rm(path.join(commandsDir, entry), { force: true });
    }
  }
  await removeStaleSkills(projectPath, written, ".claude/skills");
}

/** The hook entry Claude's settings file should hold — the compile-on-write loop. */
const CLAUDE_HOOK_COMMAND =
  'node "$CLAUDE_PROJECT_DIR/.claude/hooks/shall/check-spec.mjs"';

/** Which tools Claude fires the hook after. */
const CLAUDE_HOOK_MATCHER = "Write|Edit|MultiEdit";

/** How long either agent may wait for the compile before giving up on it. */
export const HOOK_TIMEOUT = 90;

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Merges one compile-hook entry into a `PostToolUse` list, with the deny rules'
 * own restraint: a missing file is written fresh, an unparseable or
 * wrong-shaped one is left alone, a present entry is not rewritten, and only
 * the missing entry is appended.
 *
 * IT IS THE SAME MERGE FOR BOTH AGENTS AND THE FILE IS THE DIFFERENCE. Claude
 * reads its hooks out of `.claude/settings.json`, which is a person's file with
 * other things in it; Codex reads them out of `.codex/hooks.json`, which is a
 * person's file too. Same shape, same restraint, one implementation.
 *
 * THE SCRIPT'S OWN PATH IS THE PRESENCE TEST, not the whole command: somebody
 * who wired the hook themselves with a flag of their own has wired it, and a
 * second entry beside theirs would run the compile twice on every write.
 */
export async function mergeHookEntry(
  filePath: string,
  matcher: string,
  command: string,
  timeout: number,
): Promise<void> {
  const entry = {
    matcher,
    hooks: [{ type: "command", command, timeout }],
  };
  const wired = (command.split(" ").at(-1) ?? command).replaceAll('"', "");

  const current = await readFile(filePath, "utf8").catch(
    (error: NodeJS.ErrnoException) => {
      if (error.code === "ENOENT") {
        return null;
      }
      throw error;
    },
  );
  if (current === null) {
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeByRename(
      filePath,
      `${JSON.stringify({ hooks: { PostToolUse: [entry] } }, null, 2)}\n`,
    );
    return;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(current) as unknown;
  } catch {
    return;
  }
  if (!isPlainObject(parsed)) {
    return;
  }
  const hooks = parsed.hooks;
  if (hooks !== undefined && !isPlainObject(hooks)) {
    return;
  }
  const block: Record<string, unknown> = hooks ?? {};
  const post = block.PostToolUse;
  if (post !== undefined && !Array.isArray(post)) {
    return;
  }
  const entries: unknown[] = post ?? [];
  const present = entries.some((held) => JSON.stringify(held).includes(wired));
  if (present) {
    return;
  }
  block.PostToolUse = [...entries, entry];
  parsed.hooks = block;
  await writeByRename(filePath, `${JSON.stringify(parsed, null, 2)}\n`);
}

/**
 * THE CLAUDE LAYOUT — everything the kit writer was before it had a second
 * agent to write for, said as data.
 */
export const CLAUDE_LAYOUT: KitLayout = {
  agent: "claude",
  embeddedPrefix: "kit/claude/",
  root: () => generatedRoot("claude"),
  walk: claudeWalk,
  targetOf: claudeTargetOf,
  transform: claudeDialect,
  removeStale: claudeRemoveStale,
  wireHooks: (projectPath) =>
    mergeHookEntry(
      getAgentSettingsPath(projectPath),
      CLAUDE_HOOK_MATCHER,
      CLAUDE_HOOK_COMMAND,
      HOOK_TIMEOUT,
    ),
};

/**
 * Writes one agent's whole kit into a project, rewriting only what differs and
 * removing only what the marker proves is Shall's.
 */
export async function writeKit(
  projectPath: string,
  layout: KitLayout,
): Promise<void> {
  try {
    const kit = await kitOf(layout);
    const written = new Set(kit.map((file) => file.to));
    await Promise.all(
      kit.map((file) =>
        writeIfChanged(path.join(projectPath, ...file.to.split("/")), file.content),
      ),
    );
    await layout.removeStale(projectPath, written);
    await layout.wireHooks(projectPath);
  } catch {
    // Silence, deliberately: wiring is a convenience, not a condition.
  }
}

/** The Claude kit, by the name every caller had for it before the adapters. */
export async function writeAgentKit(projectPath: string): Promise<void> {
  await writeKit(projectPath, CLAUDE_LAYOUT);
}
