import { mkdir, readdir, readFile, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SHALL_VERSION } from "@shall/core/version";
import { writeByRename } from "./atomic-write.js";
import { getAgentSettingsPath } from "./agent-settings.js";
import { isEmbedded, listEmbedded, readEmbeddedText } from "./embedded.js";

/**
 * THE AGENT KIT: the plugin's commands, skills and compile hook, written into a
 * project's own `.claude/` so that being a Shall project IS being wired — no
 * install step, no `--plugin-dir`, no second procedure. `shall init` writes the
 * kit and every open rewrites whatever drifted, exactly as the rules page and
 * the deny rules are handled next door.
 *
 * THE PLUGIN STAYS THE ONE SOURCE. Nothing here is a second copy of the
 * process prose: the kit is read out of the repository's `agents/claude/` folder at
 * write time and transformed for the project-command dialect: the colon
 * namespace is the plugin form and a project command cannot wear it, so
 * `/shall:specify` becomes `/shall.specify`, a skill is called by its bare
 * name, and the hook runs from the project's own folder. The plugin folder
 * stays the source of the text; the kit is that text in the project's
 * grammar.
 *
 * EVERY GENERATED FILE CARRIES THE MARKER, and the marker is the ownership
 * test: stale `shall.*` commands and `shall-*` skills are removed only when
 * they carry it, so a person's own file that happens to share the prefix is
 * never Shall's to delete. THE MARKER'S OWN WORDS NEVER MOVE — a kit written
 * by an older Shall has to go on matching, or the day it is upgraded is the day
 * its files stop being Shall's and are left behind for ever.
 *
 * UNDER THE MARKER SITS THE VERSION THAT WROTE THE FILE, which is what makes an
 * upgrade visible: the write below compares bytes, and a moved version moves
 * every file in the kit, so a project opened by a new Shall is regenerated
 * whole rather than left carrying last release's prose.
 *
 * IT NEVER THROWS, for the reason its neighbours do not: wiring is an
 * open-time convenience, not a condition of opening a project.
 */

const moduleDirectory = path.dirname(fileURLToPath(import.meta.url));

/**
 * The Claude plugin folder of the checkout this daemon runs from — src and dist
 * sit at the same depth. It lives under `agents/` because Claude is the first
 * agent Shall drives, not the last; a codex kit would be its sibling.
 *
 * A SINGLE-BINARY SHALL HAS NO CHECKOUT BEHIND IT, so it carries the same
 * folder as bytes and `pluginFiles` reads those instead. What is carried is
 * what the walk below would have found, which is why the two sources can share
 * every line after them.
 */
function pluginRoot(): string {
  return path.resolve(moduleDirectory, "..", "..", "..", "agents", "claude");
}

/**
 * The one line that marks a generated file as Shall's to rewrite and to remove.
 *
 * ITS BYTES ARE FROZEN. Ownership is tested by this exact string, and every kit
 * any Shall ever wrote carries it — so the version that wrote a file is said on
 * the line below rather than in here, where a new word would orphan every kit
 * older than it.
 */
export const KIT_MARKER =
  "<!-- Generated by Shall from its plugin. Rewritten whenever this project is opened; edits here are overwritten. -->";

/** Which Shall wrote the file — the second line of every marked one. */
const KIT_VERSION_LINE = `<!-- Version: ${SHALL_VERSION} -->`;

/**
 * The plugin dialect, said in the project's grammar. Order matters — the
 * namespaced skill specifier is rewritten before the command names — and the
 * leading slash on the command pattern keeps `Bash(shall:*)` untouched.
 */
function transform(text: string): string {
  return text
    .replaceAll("shall:shall-", "shall-")
    .replaceAll("/shall:", "/shall.")
    .replaceAll("${CLAUDE_PLUGIN_ROOT}/skills/", ".claude/skills/")
    .replaceAll("${CLAUDE_PLUGIN_ROOT}/hooks/", ".claude/hooks/shall/");
}

/** The marker and the version under it, seated after the frontmatter where there is one, so the frontmatter stays first. */
function withMarker(text: string): string {
  const head = `${KIT_MARKER}\n${KIT_VERSION_LINE}`;
  if (text.startsWith("---\n")) {
    const close = text.indexOf("\n---\n", 4);
    if (close !== -1) {
      const at = close + "\n---\n".length;
      return `${text.slice(0, at)}\n${head}\n${text.slice(at)}`;
    }
  }
  return `${head}\n\n${text}`;
}

interface KitFile {
  /** Project-relative target, "/"-separated. */
  readonly to: string;
  readonly content: string;
}

/**
 * Where a plugin file lands in a project, or null when it is not part of the
 * kit. THE THREE SHAPES ARE THE WHOLE KIT: a command is renamed into the
 * project-command dialect, a skill arrives whole under its own name, and the
 * hook is the one file that is script rather than prose and so carries no
 * marker — a comment in it would be read by node, not by Claude.
 */
function targetOf(relative: string): string | null {
  const [folder, ...rest] = relative.split("/");
  if (folder === "commands" && rest.length === 1 && relative.endsWith(".md")) {
    return `.claude/commands/shall.${rest.join("/")}`;
  }
  if (folder === "skills" && rest.length > 1 && relative.endsWith(".md")) {
    return `.claude/skills/${rest.join("/")}`;
  }
  if (relative === "hooks/check-spec.mjs") {
    return ".claude/hooks/shall/check-spec.mjs";
  }
  return null;
}

/** Where the carried copy of the plugin folder sits — see `host/embedded.ts`. */
const KIT_PREFIX = "kit/";

/** Every plugin file the kit is made of, "/"-separated from the plugin root. */
async function pluginFiles(): Promise<string[]> {
  if (isEmbedded()) {
    return listEmbedded(KIT_PREFIX);
  }
  const root = pluginRoot();
  const found: string[] = [];
  for (const entry of await readdir(path.join(root, "commands"))) {
    found.push(`commands/${entry}`);
  }
  const skillsRoot = path.join(root, "skills");
  for (const skill of await readdir(skillsRoot)) {
    for (const relative of await markdownUnder(path.join(skillsRoot, skill))) {
      found.push(`skills/${skill}/${relative}`);
    }
  }
  found.push("hooks/check-spec.mjs");
  return found;
}

/** Every `.md` under a folder, as "/"-separated relative paths, in walk order. */
async function markdownUnder(folder: string, prefix = ""): Promise<string[]> {
  const found: string[] = [];
  for (const entry of await readdir(folder, { withFileTypes: true })) {
    const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      found.push(
        ...(await markdownUnder(path.join(folder, entry.name), relative)),
      );
    } else if (entry.name.endsWith(".md")) {
      found.push(relative);
    }
  }
  return found;
}

/** One plugin file's text, from the checkout or from the bytes carried. */
async function readPlugin(relative: string): Promise<string> {
  if (isEmbedded()) {
    const text = readEmbeddedText(`${KIT_PREFIX}${relative}`);
    if (text === undefined) {
      throw new Error(`Shall carries no plugin file at ${relative}`);
    }
    return text;
  }
  return readFile(path.join(pluginRoot(), ...relative.split("/")), "utf8");
}

/** Every file of the kit, read fresh from the plugin and transformed. */
async function kitOf(): Promise<KitFile[]> {
  const files: KitFile[] = [];
  for (const relative of await pluginFiles()) {
    const to = targetOf(relative);
    if (to === null) {
      continue;
    }
    const text = await readPlugin(relative);
    files.push({
      to,
      content: to.endsWith(".mjs") ? text : withMarker(transform(text)),
    });
  }
  return files;
}

/** Writes one file when its bytes differ, making the folders it needs. */
async function writeIfChanged(target: string, content: string): Promise<void> {
  if ((await readFile(target, "utf8").catch(() => null)) === content) {
    return;
  }
  await mkdir(path.dirname(target), { recursive: true });
  await writeByRename(target, content);
}

/** Removes a folder of an earlier layout, file by marker-guarded file, then the folder when empty. */
async function removeMarkedFolder(folder: string): Promise<void> {
  for (const entry of await readdir(folder).catch(() => [])) {
    const text = await readFile(path.join(folder, entry), "utf8").catch(() => "");
    if (text.includes(KIT_MARKER)) {
      await rm(path.join(folder, entry), { force: true });
    }
  }
  if ((await readdir(folder).catch(() => ["x"])).length === 0) {
    await rm(folder, { recursive: true, force: true });
  }
}

/** Removes the kit files an older kit wrote and this one no longer carries — marker-guarded. */
async function removeStale(
  projectPath: string,
  written: ReadonlySet<string>,
): Promise<void> {
  const commandsDir = path.join(projectPath, ".claude", "commands");
  for (const entry of await readdir(commandsDir).catch(() => [])) {
    const relative = `.claude/commands/${entry}`;
    if (
      !(entry.startsWith("shall.") || entry.startsWith("shall/")) &&
      entry !== "shall"
    ) {
      continue;
    }
    if (entry === "shall") {
      // The folder an earlier layout wrote; its files carry the marker.
      await removeMarkedFolder(path.join(commandsDir, entry));
      continue;
    }
    if (!entry.endsWith(".md") || written.has(relative)) {
      continue;
    }
    const text = await readFile(path.join(commandsDir, entry), "utf8").catch(
      () => "",
    );
    if (text.includes(KIT_MARKER)) {
      await rm(path.join(commandsDir, entry), { force: true });
    }
  }
  const skillsDir = path.join(projectPath, ".claude", "skills");
  const owned = new Set(
    [...written]
      .filter((held) => held.startsWith(".claude/skills/"))
      .map((held) => held.split("/")[2] ?? ""),
  );
  for (const entry of await readdir(skillsDir).catch(() => [])) {
    if (!entry.startsWith("shall-") || owned.has(entry)) {
      continue;
    }
    const page = await readFile(
      path.join(skillsDir, entry, "SKILL.md"),
      "utf8",
    ).catch(() => "");
    if (page.includes(KIT_MARKER)) {
      await rm(path.join(skillsDir, entry), { recursive: true, force: true });
    }
  }
}

/** The hook entry the settings file should hold — the compile-on-write loop. */
const HOOK_COMMAND =
  'node "$CLAUDE_PROJECT_DIR/.claude/hooks/shall/check-spec.mjs"';

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Merges the compile hook into `.claude/settings.json`, with the deny rules'
 * own restraint: a missing file is written fresh, an unparseable or
 * wrong-shaped one is left alone, a present entry is not rewritten, and only
 * the missing entry is appended.
 */
async function writeHookWiring(projectPath: string): Promise<void> {
  const settingsPath = getAgentSettingsPath(projectPath);
  const entry = {
    matcher: "Write|Edit|MultiEdit",
    hooks: [{ type: "command", command: HOOK_COMMAND, timeout: 90 }],
  };

  const current = await readFile(settingsPath, "utf8").catch(
    (error: NodeJS.ErrnoException) => {
      if (error.code === "ENOENT") {
        return null;
      }
      throw error;
    },
  );
  if (current === null) {
    await mkdir(path.dirname(settingsPath), { recursive: true });
    await writeByRename(
      settingsPath,
      `${JSON.stringify({ hooks: { PostToolUse: [entry] } }, null, 2)}\n`,
    );
    return;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(current) as unknown;
  } catch {
    return;
  }
  if (!isPlainObject(parsed)) {
    return;
  }
  const hooks = parsed.hooks;
  if (hooks !== undefined && !isPlainObject(hooks)) {
    return;
  }
  const block: Record<string, unknown> = hooks ?? {};
  const post = block.PostToolUse;
  if (post !== undefined && !Array.isArray(post)) {
    return;
  }
  const entries: unknown[] = post ?? [];
  const present = entries.some(
    (held) => JSON.stringify(held).includes(HOOK_COMMAND.slice(6, -1)),
  );
  if (present) {
    return;
  }
  block.PostToolUse = [...entries, entry];
  parsed.hooks = block;
  await writeByRename(settingsPath, `${JSON.stringify(parsed, null, 2)}\n`);
}

/**
 * Writes the whole kit into a project, rewriting only what differs and
 * removing only what the marker proves is Shall's.
 */
export async function writeAgentKit(projectPath: string): Promise<void> {
  try {
    const kit = await kitOf();
    const written = new Set(kit.map((file) => file.to));
    await Promise.all(
      kit.map((file) =>
        writeIfChanged(path.join(projectPath, ...file.to.split("/")), file.content),
      ),
    );
    await removeStale(projectPath, written);
    await writeHookWiring(projectPath);
  } catch {
    // Silence, deliberately: wiring is a convenience, not a condition.
  }
}
