import { readFile } from "node:fs/promises";
import path from "node:path";
import { writeByRename } from "./atomic-write.js";
import { KIT_VERSION_LINE } from "./agent-kit.js";

/**
 * THE BLOCK SHALL KEEPS INSIDE SOMEBODY ELSE'S `AGENTS.md`.
 *
 * WHY A FENCED BLOCK AND NOT A FILE OF SHALL'S OWN. Claude reads every file
 * under `.claude/rules/`, which is why the rules page next door can be a
 * generated document Shall owns whole. Codex has no such folder: what it reads
 * before every session is the project's `AGENTS.md`, one file, usually
 * somebody's, usually long. So the same half-page arrives here as a managed
 * span inside a document that is not Shall's — and the fences are what make
 * that survivable, for Shall and for the person both.
 *
 * THE FENCES' BYTES ARE FROZEN, for the reason `KIT_MARKER`'s are: they are how
 * a block written by an older Shall is found again, and a reworded fence would
 * leave every project's `AGENTS.md` carrying two blocks — last release's,
 * orphaned for ever, and this one's underneath it.
 *
 * WHAT IS OUTSIDE THE FENCES IS NEVER TOUCHED, and the file's own first line
 * says so, so a person who finds the block can see at a glance which half of
 * their page they own. The one thing this will not do is repair a half-broken
 * pair: exactly one fence is somebody's edit mid-flight, or a merge that went
 * wrong, and guessing where the missing one belongs would eat prose.
 *
 * IT NEVER THROWS AND IT MAKES NO FOLDERS. The project root is already there —
 * it is the folder being wired — and everything else is the open-time
 * convenience its neighbours are.
 */

/** The first fence. Frozen — see above. */
export const AGENTS_MD_BEGIN =
  "<!-- BEGIN SHALL — generated by Shall and rewritten whenever this project is opened; edits between these fences are overwritten, and nothing outside them is ever touched. -->";

/** The second. Frozen for the same reason. */
export const AGENTS_MD_END = "<!-- END SHALL -->";

/** Where the block lives, as a project-relative path for anyone reporting it. */
export const AGENTS_MD_FILE = "AGENTS.md";

/** The block as it should stand: the fences, the version that wrote it, the prose. */
function blockOf(blockBody: string): string {
  return `${AGENTS_MD_BEGIN}\n${KIT_VERSION_LINE}\n\n${blockBody.trim()}\n${AGENTS_MD_END}`;
}

/**
 * Writes the block into `<project>/AGENTS.md`, in whichever of the five states
 * that file is in:
 *
 * - No file at all: the block alone, with a trailing newline.
 * - Both fences: the span between them, inclusive, is replaced. Everything
 *   before and after stands exactly as it was.
 * - Neither fence: the block is APPENDED. A person's own instructions were
 *   written first and go on being read first; Shall's half-page arrives under
 *   them rather than in front of them.
 * - Exactly one fence: NOTHING HAPPENS. Half a pair is still somebody's work,
 *   and there is no honest place to put the other one.
 * - Already exactly this: NOT REWRITTEN. The bytes are compared first, so an
 *   open that changes nothing shows up in nobody's `git status`.
 */
export async function writeAgentsMdBlock(
  projectPath: string,
  blockBody: string,
): Promise<void> {
  try {
    const target = path.join(projectPath, AGENTS_MD_FILE);
    const block = blockOf(blockBody);

    const current = await readFile(target, "utf8").catch(
      (error: NodeJS.ErrnoException) => {
        if (error.code === "ENOENT") {
          return null;
        }
        throw error;
      },
    );
    if (current === null) {
      await writeByRename(target, `${block}\n`);
      return;
    }

    const opens = current.indexOf(AGENTS_MD_BEGIN);
    const closes = current.indexOf(AGENTS_MD_END);
    const paired = opens !== -1 && closes > opens;
    // One fence, or two in the wrong order: half a pair, and not Shall's to
    // repair. A file with neither is the append below.
    if (!paired && (opens !== -1 || closes !== -1)) {
      return;
    }

    const wanted = paired
      ? `${current.slice(0, opens)}${block}${current.slice(
          closes + AGENTS_MD_END.length,
        )}`
      : `${current}\n\n${block}\n`;
    if (wanted === current) {
      return;
    }
    await writeByRename(target, wanted);
  } catch {
    // Silence, deliberately: see above.
  }
}
