import { spawn } from "node:child_process";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * SHALL AS ONE FILE PER PLATFORM: the web app built, the two folders a checkout
 * would have been read for written out as a TypeScript module of bytes, and
 * `bun build --compile` run over the entry that hands them in.
 *
 * WHAT IS EMBEDDED IS WHAT IS READ FROM THE CHECKOUT AND NOTHING ELSE. The
 * daemon opens exactly three folders it did not make — `apps/web/dist` for the
 * pages, and one generated tree per agent under `agents/dist` for the kits — so
 * those are carried and every other read stays a read of the machine the binary
 * runs on. Anything added to that list has to be added here, or it works in a
 * checkout and is missing in the release.
 *
 * EVERY FOLDER IS BUILT BEFORE IT IS READ. `bun run build` below is what makes
 * them: it runs `build:agents` first, so the agent trees are generated from
 * `agents/core` and `agents/profiles` in the same breath as the web app, and a
 * release can never carry last generation's prose.
 *
 * THE KITS ARE FILTERED, NOT COPIED WHOLE, and each agent's filter is its
 * adapter's walk said again here. Claude's kit is the commands, the skills and
 * the one hook script — its `hooks.json` is plugin-folder wiring that no
 * project ever receives, and its manifest is not a project's either. Codex's is
 * the skills, the hook script, the hook wiring it merges from and the always-on
 * `AGENTS.md` block: the last two are inputs the adapter reads by name rather
 * than files a project is given, and a binary that did not carry them could
 * write the prose and not the wiring.
 *
 * `--local` BUILDS ONLY THIS MACHINE'S TARGET, because the other three make bun
 * fetch a runtime it does not have yet and that is a download nobody wants in
 * the middle of a change they are testing.
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");

/** The platforms Shall ships, as bun names them and as the file is named. */
const TARGETS = [
  "darwin-arm64",
  "darwin-x64",
  "linux-x64",
  "linux-arm64",
];

/** Where the compiled entry lives, and where the generated bytes land beside it. */
const ENTRY = path.join(root, "client", "cli", "binary", "entry.ts");
const GENERATED = path.join(
  root,
  "client",
  "cli",
  "binary",
  "assets.generated.ts",
);
const OUTPUT = path.join(root, "dist-bin");

function run(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: root,
      stdio: "inherit",
      ...options,
    });
    child.once("error", reject);
    child.once("exit", (code) => {
      if (code === 0) {
        resolve();
        return;
      }
      reject(new Error(`${command} ${args.join(" ")} exited with ${code}`));
    });
  });
}

/** Every file under a folder, as "/"-separated paths relative to it. */
async function filesUnder(folder, prefix = "") {
  const found = [];
  for (const entry of await readdir(folder, { withFileTypes: true })) {
    const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      found.push(...(await filesUnder(path.join(folder, entry.name), relative)));
    } else if (entry.isFile()) {
      found.push(relative);
    }
  }
  return found;
}

/**
 * Which files of one agent's generated tree the kit is made of — one predicate
 * per agent, and the agent's own folder name is the key. See the note above.
 */
const KIT_FILES = {
  claude: (relative) =>
    (relative.startsWith("commands/") && relative.endsWith(".md")) ||
    (relative.startsWith("skills/") && relative.endsWith(".md")) ||
    relative === "hooks/check-spec.mjs",
  codex: (relative) =>
    (relative.startsWith("skills/") && relative.endsWith(".md")) ||
    relative === "hooks/check-spec.mjs" ||
    relative === "hooks/hooks.json" ||
    relative === "AGENTS.md.block",
};

async function kitFiles(agentRoot, agent) {
  const wanted = KIT_FILES[agent];
  return (await filesUnder(agentRoot)).filter((relative) => wanted(relative));
}

async function carry(files, folder, relatives, prefix) {
  for (const relative of relatives) {
    const bytes = await readFile(path.join(folder, ...relative.split("/")));
    files.set(`${prefix}${relative}`, bytes.toString("base64"));
  }
}

async function generateAssets() {
  const webRoot = path.join(root, "apps", "web", "dist");
  const files = new Map();
  await carry(files, webRoot, await filesUnder(webRoot), "web/");
  // One prefix per agent, which is the name the daemon's layouts read under:
  // `kit/claude/` and `kit/codex/`.
  for (const agent of Object.keys(KIT_FILES)) {
    const agentRoot = path.join(root, "agents", "dist", agent);
    await carry(
      files,
      agentRoot,
      await kitFiles(agentRoot, agent),
      `kit/${agent}/`,
    );
  }

  const entries = [...files.keys()]
    .sort()
    .map((held) => `  ${JSON.stringify(held)}: ${JSON.stringify(files.get(held))},`)
    .join("\n");
  await writeFile(
    GENERATED,
    [
      "// Written by scripts/build-binary.mjs from apps/web/dist and",
      "// agents/dist/*. Git ignores it and every build replaces it; editing",
      "// it edits nothing, because the next build reads the folders again.",
      "export const EMBEDDED_FILES: Readonly<Record<string, string>> = {",
      entries,
      "};",
      "",
    ].join("\n"),
  );
  return files.size;
}

const asked = process.argv.slice(2);
const named = asked
  .filter((argument) => argument.startsWith("--target="))
  .map((argument) => argument.slice("--target=".length));
const unknown = asked.filter(
  (argument) => argument !== "--local" && !argument.startsWith("--target="),
);
if (unknown.length > 0) {
  throw new Error(`Unknown option: ${unknown.join(", ")}`);
}
const local = asked.includes("--local")
  ? [`${process.platform === "darwin" ? "darwin" : "linux"}-${process.arch}`]
  : [];
const targets = [...named, ...local];
const building = targets.length > 0 ? targets : TARGETS;
for (const target of building) {
  if (!TARGETS.includes(target)) {
    throw new Error(`Shall does not ship a ${target} binary`);
  }
}

await run("bun", ["run", "build"]);
const carried = await generateAssets();
console.log(`Embedded ${carried} files.`);
await mkdir(OUTPUT, { recursive: true });

/**
 * `bun build --compile` writes the target runtime into the working directory
 * before it seals the executable, and a compile that is interrupted leaves the
 * sixty megabytes behind. It runs from the output folder so that anything left
 * over lands somewhere git already ignores, and the sweep below takes it from
 * there.
 */
async function sweep() {
  for (const entry of await readdir(OUTPUT)) {
    if (entry.endsWith(".bun-build")) {
      await rm(path.join(OUTPUT, entry), { force: true });
    }
  }
}

for (const target of building) {
  const outfile = path.join(OUTPUT, `shall-${target}`);
  await run("bun", [
    "build",
    "--compile",
    // `bun build` inlines `process.env.NODE_ENV` and calls it "development"
    // unless it is told otherwise. Every library in the bundle reads that name
    // for its own reasons, and a release that says development to all of them
    // is a release full of dev-only warnings and slow paths.
    "--define",
    'process.env.NODE_ENV="production"',
    `--target=bun-${target}`,
    ENTRY,
    "--outfile",
    outfile,
  ], { cwd: OUTPUT });
  await sweep();
  console.log(`Built ${path.relative(root, outfile)}`);
}
