import { spawn } from "node:child_process";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * SHALL AS ONE FILE PER PLATFORM: the web app built, the two folders a checkout
 * would have been read for written out as a TypeScript module of bytes, and
 * `bun build --compile` run over the entry that hands them in.
 *
 * WHAT IS EMBEDDED IS WHAT IS READ FROM THE CHECKOUT AND NOTHING ELSE. The
 * daemon opens exactly two folders it did not make — `apps/web/dist` for the
 * pages and `agents/dist/claude` for the agent kit — so those two are carried
 * and every other read stays a read of the machine the binary runs on. Anything
 * added to that list has to be added here, or it works in a checkout and is
 * missing in the release.
 *
 * BOTH FOLDERS ARE BUILT BEFORE THEY ARE READ. `bun run build` below is what
 * makes them: it runs `build:agents` first, so the agent tree is generated from
 * `agents/core` and `agents/profiles` in the same breath as the web app, and a
 * release can never carry last generation's prose.
 *
 * THE KIT IS FILTERED, NOT COPIED WHOLE. `agent-kit.ts` walks the plugin for
 * the commands, the skills and the one hook; embedding the same set keeps the
 * two sources answering identically, and keeps the plugin's manifest — which no
 * project ever receives — out of the executable.
 *
 * `--local` BUILDS ONLY THIS MACHINE'S TARGET, because the other three make bun
 * fetch a runtime it does not have yet and that is a download nobody wants in
 * the middle of a change they are testing.
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");

/** The platforms Shall ships, as bun names them and as the file is named. */
const TARGETS = [
  "darwin-arm64",
  "darwin-x64",
  "linux-x64",
  "linux-arm64",
];

/** Where the compiled entry lives, and where the generated bytes land beside it. */
const ENTRY = path.join(root, "client", "cli", "binary", "entry.ts");
const GENERATED = path.join(
  root,
  "client",
  "cli",
  "binary",
  "assets.generated.ts",
);
const OUTPUT = path.join(root, "dist-bin");

function run(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: root,
      stdio: "inherit",
      ...options,
    });
    child.once("error", reject);
    child.once("exit", (code) => {
      if (code === 0) {
        resolve();
        return;
      }
      reject(new Error(`${command} ${args.join(" ")} exited with ${code}`));
    });
  });
}

/** Every file under a folder, as "/"-separated paths relative to it. */
async function filesUnder(folder, prefix = "") {
  const found = [];
  for (const entry of await readdir(folder, { withFileTypes: true })) {
    const relative = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      found.push(...(await filesUnder(path.join(folder, entry.name), relative)));
    } else if (entry.isFile()) {
      found.push(relative);
    }
  }
  return found;
}

/** The plugin files the agent kit is made of — see the note above. */
async function kitFiles(pluginRoot) {
  const wanted = [];
  for (const relative of await filesUnder(pluginRoot)) {
    const [folder] = relative.split("/");
    if (folder === "commands" && relative.endsWith(".md")) {
      wanted.push(relative);
    } else if (folder === "skills" && relative.endsWith(".md")) {
      wanted.push(relative);
    } else if (relative === "hooks/check-spec.mjs") {
      wanted.push(relative);
    }
  }
  return wanted;
}

async function carry(files, folder, relatives, prefix) {
  for (const relative of relatives) {
    const bytes = await readFile(path.join(folder, ...relative.split("/")));
    files.set(`${prefix}${relative}`, bytes.toString("base64"));
  }
}

async function generateAssets() {
  const webRoot = path.join(root, "apps", "web", "dist");
  const pluginRoot = path.join(root, "agents", "dist", "claude");
  const files = new Map();
  await carry(files, webRoot, await filesUnder(webRoot), "web/");
  await carry(files, pluginRoot, await kitFiles(pluginRoot), "kit/");

  const entries = [...files.keys()]
    .sort()
    .map((held) => `  ${JSON.stringify(held)}: ${JSON.stringify(files.get(held))},`)
    .join("\n");
  await writeFile(
    GENERATED,
    [
      "// Written by scripts/build-binary.mjs from apps/web/dist and",
      "// agents/dist/claude. Git ignores it and every build replaces it; editing",
      "// it edits nothing, because the next build reads the folders again.",
      "export const EMBEDDED_FILES: Readonly<Record<string, string>> = {",
      entries,
      "};",
      "",
    ].join("\n"),
  );
  return files.size;
}

const asked = process.argv.slice(2);
const named = asked
  .filter((argument) => argument.startsWith("--target="))
  .map((argument) => argument.slice("--target=".length));
const unknown = asked.filter(
  (argument) => argument !== "--local" && !argument.startsWith("--target="),
);
if (unknown.length > 0) {
  throw new Error(`Unknown option: ${unknown.join(", ")}`);
}
const local = asked.includes("--local")
  ? [`${process.platform === "darwin" ? "darwin" : "linux"}-${process.arch}`]
  : [];
const targets = [...named, ...local];
const building = targets.length > 0 ? targets : TARGETS;
for (const target of building) {
  if (!TARGETS.includes(target)) {
    throw new Error(`Shall does not ship a ${target} binary`);
  }
}

await run("bun", ["run", "build"]);
const carried = await generateAssets();
console.log(`Embedded ${carried} files.`);
await mkdir(OUTPUT, { recursive: true });

/**
 * `bun build --compile` writes the target runtime into the working directory
 * before it seals the executable, and a compile that is interrupted leaves the
 * sixty megabytes behind. It runs from the output folder so that anything left
 * over lands somewhere git already ignores, and the sweep below takes it from
 * there.
 */
async function sweep() {
  for (const entry of await readdir(OUTPUT)) {
    if (entry.endsWith(".bun-build")) {
      await rm(path.join(OUTPUT, entry), { force: true });
    }
  }
}

for (const target of building) {
  const outfile = path.join(OUTPUT, `shall-${target}`);
  await run("bun", [
    "build",
    "--compile",
    // `bun build` inlines `process.env.NODE_ENV` and calls it "development"
    // unless it is told otherwise. Every library in the bundle reads that name
    // for its own reasons, and a release that says development to all of them
    // is a release full of dev-only warnings and slow paths.
    "--define",
    'process.env.NODE_ENV="production"',
    `--target=bun-${target}`,
    ENTRY,
    "--outfile",
    outfile,
  ], { cwd: OUTPUT });
  await sweep();
  console.log(`Built ${path.relative(root, outfile)}`);
}
